apiVersion: v1
kind: LimitRange
metadata:
  name: build-limitrange
spec:
  limits:
    - default:
        cpu: 16
        memory: 64Gi
      defaultRequest:
        cpu: 16
        memory: 64Gi
      max:
        cpu: 32
        memory: 256Gi
      min:
        cpu: 1
        memory: 1Gi
      type: Container
