apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  name: amd-gpu
spec:
  machineConfigSelector:
    matchLabels:
      machineconfiguration.openshift.io/extra: amd-gpu
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/amd-gpu-test: ''
