---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: job-restart-operator
  annotations:
    argocd.argoproj.io/sync-wave: "3"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-restart-operator
rules:
  - apiGroups:
      - ""
    resources:
      - pod
    verbs:
      - get
      - list
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-restart-operator
  annotations:
    argocd.argoproj.io/sync-wave: "3"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: job-restart-operator
subjects:
- kind: ServiceAccount
  name: job-restart-operator
---
apiVersion: batch/v1
kind: Job
metadata:
  name: job-restart-operator
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  template:
    spec:
      containers:
        - name: minion
          image: registry.redhat.io/openshift4/ose-cli
          command:
            - /bin/bash
            - -c
            - /scripts/job.sh
          volumeMounts:
            - name: scripts
              mountPath: /scripts
      volumes:
        - name: scripts
          configMap:
            name: job-restart-operator
            defaultMode: 0755
      restartPolicy: Never
      serviceAccount: job-restart-operator
      serviceAccountName: job-restart-operator
  backoffLimit: 4
