kind: ConfigMap
apiVersion: v1
metadata:
  name: kmm-operator-manager-config
  namespace: openshift-kmm
  labels:
    app.kubernetes.io/component: kmm
    app.kubernetes.io/name: kmm
    app.kubernetes.io/part-of: kmm
    operators.coreos.com/kernel-module-management.openshift-kmm: ''
data:
  controller_config.yaml: |
    healthProbeBindAddress: :8081
    leaderElection:
      enabled: true
      resourceID: kmm.sigs.x-k8s.io
    webhook:
      disableHTTP2: true  # CVE-2023-44487
      port: 9443
    metrics:
      enableAuthnAuthz: true
      disableHTTP2: true  # CVE-2023-44487
      bindAddress: 0.0.0.0:8443
      secureServing: true
    worker:
      runAsUser: 0
      seLinuxType: spc_t
      setFirmwareClassPath: /var/lib/firmware
